In [15]:
import tensorflow as tf
import numpy as np


data = np.reshape(np.arange(30), [5, 6])
print(data)
x = tf.constant(data)
res = tf.gather(x, [[1,2],[3,4]])
print(np.array([[1,2],[3,4]]).shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
(2, 2)


In [16]:
with tf.Session() as sess:
  print(sess.run(res))
  print(sess.run(res).shape)
  

[[[ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]]]
(2, 2, 6)
